-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT into friend (name) VALUES ('Gareth');
-- INSERT into friend (name) VALUES ('Mike');
-- INSERT into friend (name) VALUES ('Vincent');
